[project]
name = "todo-app-ph3"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-dotenv",
    "openai>=1.0.0",
    "sqlmodel",
    "psycopg2-binary",
    "alembic",
    "pytest",
    "pytest-asyncio",
    "httpx",
    "flake8",
    "black",
    "passlib[argon2]",
    "argon2-cffi",
    "python-jose[cryptography]",
    "python-multipart",
]

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
