apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-app-config
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
data:
  BACKEND_API_URL: {{ .Values.frontend.env.BACKEND_API_URL | quote }}